[package]
name = "dora"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
polars = "0.46.0"
ratatui = "0.29.0"
rayon = "1.10.0"
thiserror = "2.0.12"
tui-input = { version = "0.12", features = ["crossterm"] }
